---
title: '1111'
author: "jgh0208"
date: '2019 11 11 '
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#이항로지스틱-로짓변환
```{r}
eta <- seq(-10,10,length=1000)
plot(eta)

f <- function(eta) exp(eta)/(1+exp(eta))
f(2)
f(eta)
#x축은 n값이고 y축은 f(eta)
plot(f(eta))
```

#데이터불러오기
```{r}
lungcancer <- read.table("../data/lung-cancer.txt",header=T)
```
#이항로지스틱분석-변수선택법
```{r}
#install.packages("car")
library(car)
# LC:폐암여부, SEX:성별, BK:인종, SS:, AG:나이, YR:

#그냥 모든 변수들을 다 넣고 돌렸을때 
flca <- glm(LC~SEX+BK+SS+AG+YR,data = lungcancer,family = binomial)
flca  
summary(flca)  

#전진선택법으로 변수를 선택했을 때
(flcf <- step(glm(LC~.,data = lungcancer,family = binomial),direction = "forward"))
summary(flcf)
vif(flcf)
#후진제거법으로 변수를 선택했을 때
(flcb <- step(glm(LC~.,data = lungcancer,family = binomial),direction = "backward"))
summary(flcb)
vif(flcb)
#단계적선택법으로 변수를 선택했을 때
(flcs <- step(glm(LC~.,data = lungcancer,family = binomial),direction = "both"))
summary(flcs)
vif(flcs)

```
#검정통계량-우도비검정 
```{r}
#install.packages("rms")
library(rms)
lrm(flcb)
```

#이항로지스틱-Roc
```{r}
#install.packages("pROC")
library(pROC)

rocb <- roc(formula=LC~as.numeric(BK),data = lungcancer)  
plot(rocb,col="red")   
rocy <- roc(formula=LC~YR,data = lungcancer)  
plot(rocy,add=T,col="purple")   

auc(rocb)
auc(rocy)

#plot.roc의 옵션에서 자동으로 cutoff를 알아낼수있다. 

plot.roc(rocb,   # roc를 계산한 value를 입력합니다.
         col="red",   # 선의 색상을 설정합니다.
         print.auc=TRUE,   # auc 값을 출력하도록 설정합니다.
         max.auc.polygon=TRUE,   # auc의 최대 면적을 출력하도록 설정합니다.
         print.thres=TRUE, print.thres.pch=19, print.thres.col = "red",   # 기준치(cut-off value)에 대한 출력, 포인트, 색상을 설정합니다.
         auc.polygon=TRUE, auc.polygon.col="#D1F2EB")   # 선 아래 면적에 대한 출력, 색상을 설정합니다. 
plot.roc(rocy,   # roc를 계산한 value를 입력합니다.
         col="red",   # 선의 색상을 설정합니다.
         print.auc=TRUE,   # auc 값을 출력하도록 설정합니다.
         max.auc.polygon=TRUE,   # auc의 최대 면적을 출력하도록 설정합니다.
         print.thres=TRUE, print.thres.pch=19, print.thres.col = "red",   # 기준치(cut-off value)에 대한 출력, 포인트, 색상을 설정합니다.
         auc.polygon=TRUE, auc.polygon.col="#D1F2EB")   # 선 아래 면적에 대한 출력, 색상을 설정합니다.

```

#이항로지스틱-ROC-직접그려보기
```{r}
#예측모델로 Y의 추정치 구하기
lungcancer$yestimate <- predict(flcb,newdata = list(BK=lungcancer$BK,YR=lungcancer$YR),type = "response")

#cutoff를 구하기 위한 구간을 만들어주기
co <- seq(0.01,1,by=0.01)

#install.packages("caret")
library(caret)
#install.packages("ROCR")
library(ROCR)
codf <- data.frame(codf <- lungcancer$LC)
for (i in 1:length(co)) {
  codf[,i+1] <- ifelse(lungcancer$yestimate>co[i],1,0)
}
colnames(codf) <- c("Y",paste0(rep("yh",100),seq(1,100,by=1)))
codf
rlc <- sum(codf$Y==1)
rnlc <- sum(codf$Y==0)
cdf <- as.data.frame(co)


#for (i in 1:length(co)) {
#  if(codf[,1]==codf[,i+1]){
#    ss <- sum(codf[,1]==codf[,i+1])
#    sds <- codf[which(codf[,1]==codf[,i+1]),c(1,i+1)]
#    if(sds==1){
#      srlc <- sum(sds==1)
#      cdf[i,2] <- (srlc/rlc)
#    }else snrlc <- (ss-srlc)
#          cdf[i,3] <- (snrlc/rnlc)
#  }
#  
#}



for (j in 1:length(co)){
  if(codf[,1]==0 & codf[,j+1]==0){
     speci <- sum(codf[,1]==0 & codf[,j+1]==0)
     cdf[j,3] <- (speci/rnlc)
     }}



#민감도 
for (i in 1:length(co)) {
  a <- table(codf[,1],codf[,i+1])
  ifelse(is.na(a[4]),0,a[4])
  ifelse(is.na(a[2]),0,a[2])
  cdf[i,2] <- ifelse(is.na((a[4]/(a[2]+a[4]))),0,(a[4]/(a[2]+a[4])))
}

#특이도
for (i in 1:length(co)) {
  a <- table(codf[,1],codf[,i+1])
  ifelse(is.na(a[3]),0,a[3])
  ifelse(is.na(a[1]),0,a[1])
  cdf[i,3] <- ifelse(is.na((a[1]/(a[1]+a[3]))),0,(a[1]/(a[1]+a[3])))
}

#1-특이도 
cdf[,4] <- 1-cdf[,3]

colnames(cdf) <- c("cutoff","sensitivity","specificity","1-specificity")

#roc
plot(cdf$`1-specificity`,cdf$sensitivity,type = "p",
     xlab = "1-specificity",ylab = "sensitivity",pch=19,col="blue")

#####cutoff-point구하기 

#정분류율 accuracy
for (i in 1:length(co)) {
  a <- table(codf[,1],codf[,i+1])
  ifelse(is.na(a[4]),0,a[4])
  ifelse(is.na(a[2]),0,a[2])
  ifelse(is.na(a[3]),0,a[3])
  ifelse(is.na(a[1]),0,a[1])
  cdf[i,5] <- ifelse(is.na((a[1]+a[3]/(a[1]+a[3]+a[2]+a[4]))),0,(a[1]+a[3]/(a[1]+a[3]+a[2]+a[4])))
}
colnames(cdf) <- c("cutoff","sensitivity","specificity","1-specificity","accuracy")

#정분류율이 가장 높은 cutoff값알아보기????근데 값ㅇ이 이상함 정분류율이 아니라 민감도와 특이도가 가장큰부분을 봐야하는거아닌가?
which(max(cdf$accuracy)==cdf$accuracy)
cdf[73:76,]
table(codf[,1],codf[,73])
table(codf[,1],codf[,74])
table(codf[,1],codf[,75])
table(codf[,1],codf[,76])

which(max(cdf$V6)==cdf$V6)


#그래프로 그려서 나타내보기
plot(cdf$`1-specificity`,cdf$sensitivity,type = "p",
     xlab = "1-specificity",ylab = "sensitivity",pch=19,col="blue")
par(new=T)
plot(cdf$`1-specificity`[39],cdf$sensitivity[39],add=T,
     xlim = c(0,1),ylim = c(0,1),type = "p",pch=8,col="red",
     xlab = "",ylab = "")


#plot(cdf$`1-specificity`[73],cdf$sensitivity[73],add=T,type = "p",
#     pch=8,col="red",xlab = "",ylab = "")






```
